version: '3'

volumes:
  mysql_data:
  wordpress_data:
  my-website:

services:
  database:
    image: mysql:8.0.27
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    networks:
      - wordpress-network
  
  apache: 
    image: httpd:2.4
    ports: 
      - '80:80'
    volumes:
      - my-website:/var/lib/apache2/htdocs
    networks:
      - wordpress-network

  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: root_password
    networks:
      - wordpress-network

  wordpress:
    depends_on:
      - database

    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html/wp-content
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRES_DB_HOST: database:3306
      WORDPRES_DB_NAME: wordpress
      WORDPRES_DB_USER: username
      WORDPRES_DB_PASSWORD: password
    networks:
      - wordpress-network

networks:
  wordpress-network:
    driver: bridge